import fs from "fs/promises";
import path from "path";
import { createRequire } from "module";
import { fileURLToPath, pathToFileURL } from "url";

const __filename = fileURLToPath(import.meta.url);
const snapshotsDir = path.dirname(__filename);
const root = path.resolve(snapshotsDir, "../..");
const envPath = path.join(root, ".env");
const backendEnvPath = path.join(root, "backend", ".env");
const backendPackageUrl = pathToFileURL(path.join(root, "backend", "package.json"));
const requireFromBackend = createRequire(backendPackageUrl);
const mysql = requireFromBackend("mysql2/promise");

async function loadEnvFile(filePath, override = false) {
  try {
    const text = await fs.readFile(filePath, "utf8");
    for (const rawLine of text.split(/\r?\n/)) {
      const line = rawLine.trim();
      if (!line || line.startsWith("#") || !line.includes("=")) continue;
      const [key, ...rest] = line.split("=");
      if (override || !process.env[key.trim()]) {
        process.env[key.trim()] = rest.join("=").trim();
      }
    }
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
}

async function loadEnv() {
  await loadEnvFile(envPath, false);
  await loadEnvFile(backendEnvPath, true);
}

function sqlIdentifier(name) {
  return `\`${String(name).replace(/`/g, "``")}\``;
}

function sqlValue(value) {
  if (value === null || value === undefined) return "NULL";
  if (Buffer.isBuffer(value)) return `X'${value.toString("hex")}'`;
  if (value instanceof Date) {
    const pad = (n) => String(n).padStart(2, "0");
    const y = value.getFullYear();
    const m = pad(value.getMonth() + 1);
    const d = pad(value.getDate());
    const hh = pad(value.getHours());
    const mm = pad(value.getMinutes());
    const ss = pad(value.getSeconds());
    return `'${y}-${m}-${d} ${hh}:${mm}:${ss}'`;
  }
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "bigint") return String(value);
  return `'${String(value).replace(/\\/g, "\\\\").replace(/'/g, "''")}'`;
}

async function main() {
  await loadEnv();

  const dbName = process.env.DB_NAME || "agoda_clone";
  const conn = await mysql.createConnection({
    host: process.env.DB_HOST || "localhost",
    port: Number(process.env.DB_PORT || 3306),
    user: process.env.DB_USER || "root",
    password: process.env.DB_PASSWORD || "",
    database: dbName,
    dateStrings: true,
  });

  try {
    const [tableRows] = await conn.query("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'");
    const tableKey = `Tables_in_${dbName}`;
    const tables = tableRows
      .map((row) => row[tableKey] || Object.values(row)[0])
      .filter(Boolean)
      .sort();

    const now = new Date().toISOString();
    const schemaParts = [
      `-- Generated by database/snapshots/export.mjs at ${now}`,
      `-- Database: ${dbName}`,
      "SET FOREIGN_KEY_CHECKS = 0;",
      "",
    ];

    for (const table of [...tables].reverse()) {
      schemaParts.push(`DROP TABLE IF EXISTS ${sqlIdentifier(table)};`);
    }
    schemaParts.push("");

    for (const table of tables) {
      const [rows] = await conn.query(`SHOW CREATE TABLE ${sqlIdentifier(table)}`);
      const createSql = rows[0]["Create Table"];
      schemaParts.push(`${createSql};`, "");
    }
    schemaParts.push("SET FOREIGN_KEY_CHECKS = 1;", "");

    const dataParts = [
      `-- Generated by database/snapshots/export.mjs at ${now}`,
      `-- Database: ${dbName}`,
      "SET FOREIGN_KEY_CHECKS = 0;",
      "",
    ];

    for (const table of tables) {
      const [rows, fields] = await conn.query(`SELECT * FROM ${sqlIdentifier(table)}`);
      if (!rows.length) continue;
      const columns = fields.map((field) => field.name);
      dataParts.push(`-- Data for ${table}`);
      for (const row of rows) {
        const columnSql = columns.map(sqlIdentifier).join(", ");
        const valueSql = columns.map((column) => sqlValue(row[column])).join(", ");
        dataParts.push(`INSERT INTO ${sqlIdentifier(table)} (${columnSql}) VALUES (${valueSql});`);
      }
      dataParts.push("");
    }
    dataParts.push("SET FOREIGN_KEY_CHECKS = 1;", "");

    await fs.writeFile(path.join(snapshotsDir, "schema.sql"), schemaParts.join("\n"), "utf8");
    await fs.writeFile(path.join(snapshotsDir, "data.sql"), dataParts.join("\n"), "utf8");
  } finally {
    await conn.end();
  }
}

if (process.argv[1] === __filename) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

export { main as exportDataSync };