import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

import {
  backendDir,
  databaseUrl,
  loadDatabaseEnv,
  parseDatabaseUrl,
  projectRoot,
  runPgTool,
  snapshotsDir,
} from "../scripts/postgres-tools.mjs";

const __filename = fileURLToPath(import.meta.url);
const schemaOut = path.join(snapshotsDir, "schema.sql");
const dataOut = path.join(snapshotsDir, "data.sql");
const requireFromBackend = createRequire(path.join(backendDir, "package.json"));

function pgToolUrl(rawUrl) {
  const url = new URL(rawUrl);
  url.searchParams.delete("schema");
  return url.toString();
}

function quoteIdent(name) {
  return `"${String(name).replace(/"/g, '""')}"`;
}

function sqlValue(value) {
  if (value === null || value === undefined) return "NULL";
  if (Buffer.isBuffer(value)) return `decode('${value.toString("hex")}', 'hex')`;
  if (value instanceof Date) return `'${value.toISOString().replace("T", " ").replace("Z", "+00")}'`;
  if (typeof value === "bigint") return value.toString();
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "object") return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  return `'${String(value).replace(/'/g, "''")}'`;
}

function removeLegacyAuditPayloads(sql) {
  return sql
    .split(/\r?\n/)
    .filter((line) => !line.startsWith("INSERT INTO public.legacy_source_rows VALUES") || !line.includes("'audit_logs'"))
    .join("\n");
}

export async function exportSchemaSync() {
  await loadDatabaseEnv();
  await fs.mkdir(snapshotsDir, { recursive: true });

  const url = databaseUrl();
  const pgUrl = pgToolUrl(url);
  const parsed = parseDatabaseUrl(url);
  let schemaSql;

  try {
    const output = await runPgTool("pg_dump", [
      "--dbname",
      pgUrl,
      "--schema=public",
      "--schema-only",
      "--clean",
      "--if-exists",
      "--no-owner",
      "--no-privileges",
    ], { stdio: ["ignore", "pipe", "inherit"] });
    schemaSql = output.stdout.trim();
  } catch (error) {
    const migrationPath = path.join(backendDir, "prisma", "migrations", "20260513155207_init_schema", "migration.sql");
    const migrationSql = await fs.readFile(migrationPath, "utf8");
    schemaSql = [
      "-- Fallback schema generated from Prisma migration because pg_dump is unavailable.",
      "DROP SCHEMA IF EXISTS public CASCADE;",
      "CREATE SCHEMA public;",
      "",
      migrationSql.trim(),
    ].join("\n");
    console.warn(`pg_dump unavailable, using Prisma migration snapshot instead: ${error.message}`);
  }

  const content = [
    `-- PostgreSQL schema snapshot for can_lam.`,
    `-- Generated by database/snapshots/export.mjs at ${new Date().toISOString()}.`,
    `-- Database: ${parsed.database}`,
    "",
    schemaSql,
    "",
  ].join("\n");

  await fs.writeFile(schemaOut, content, "utf8");
}

export async function exportDataSync() {
  await loadDatabaseEnv();
  await fs.mkdir(snapshotsDir, { recursive: true });

  const url = databaseUrl();
  const pgUrl = pgToolUrl(url);
  const parsed = parseDatabaseUrl(url);
  let dataSql;

  try {
    const output = await runPgTool("pg_dump", [
      "--dbname",
      pgUrl,
      "--schema=public",
      "--data-only",
      "--no-owner",
      "--no-privileges",
    ], { stdio: ["ignore", "pipe", "inherit"] });
    dataSql = output.stdout.trim();
  } catch (error) {
    console.warn(`pg_dump unavailable, exporting data through Prisma instead: ${error.message}`);
    dataSql = await exportDataWithPrisma();
  }

  const content = [
    `-- PostgreSQL data snapshot for can_lam.`,
    `-- Generated by database/snapshots/export.mjs at ${new Date().toISOString()}.`,
    `-- Database: ${parsed.database}`,
    "-- Apply after snapshots/schema.sql.",
    "",
    removeLegacyAuditPayloads(dataSql),
    "",
  ].join("\n");

  await fs.writeFile(dataOut, content, "utf8");
}

async function exportDataWithPrisma() {
  const { PrismaClient } = requireFromBackend("@prisma/client");
  const prisma = new PrismaClient();
  try {
    const tableRows = await prisma.$queryRaw`
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `;
    const parts = [
      "-- Data exported through Prisma fallback.",
      "SET session_replication_role = replica;",
      "",
    ];

    for (const { table_name: tableName } of tableRows) {
      const columnRows = await prisma.$queryRawUnsafe(
        `SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = $1 ORDER BY ordinal_position`,
        tableName,
      );
      const columns = columnRows.map((row) => row.column_name);
      if (!columns.length) continue;

      const rows = await prisma.$queryRawUnsafe(`SELECT * FROM ${quoteIdent(tableName)}`);
      if (!rows.length) continue;

      parts.push(`-- Data for ${quoteIdent(tableName)}`);
      for (const row of rows) {
        const columnSql = columns.map(quoteIdent).join(", ");
        const valueSql = columns.map((column) => sqlValue(row[column])).join(", ");
        parts.push(`INSERT INTO ${quoteIdent(tableName)} (${columnSql}) VALUES (${valueSql});`);
      }
      parts.push("");
    }

    const sequenceRows = await prisma.$queryRaw`
      SELECT sequence_name
      FROM information_schema.sequences
      WHERE sequence_schema = 'public'
      ORDER BY sequence_name
    `;
    for (const { sequence_name: sequenceName } of sequenceRows) {
      const [{ last_value: lastValue }] = await prisma.$queryRawUnsafe(
        `SELECT last_value FROM ${quoteIdent(sequenceName)}`,
      );
      parts.push(`SELECT setval('${sequenceName.replace(/'/g, "''")}', ${lastValue}, true);`);
    }

    parts.push("", "SET session_replication_role = origin;");
    return parts.join("\n");
  } finally {
    await prisma.$disconnect();
  }
}

export async function exportAll() {
  await exportSchemaSync();
  await exportDataSync();
  console.log(`Snapshot export completed:`);
  console.log(`- ${schemaOut}`);
  console.log(`- ${dataOut}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  exportAll().catch((error) => {
    console.error(error.message || error);
    process.exitCode = 1;
  });
}
