-- PostgreSQL schema snapshot for can_lam.
-- Generated by database/snapshots/export.mjs at 2026-05-30T04:57:22.088Z.
-- Database: nowayhome

--
-- PostgreSQL database dump
--

\restrict d6H5SbcSwpeaacMbynFBqKkH8HW8Se99obBevzkdi1TDOmCEfVJqObAPpaa4f22

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.vouchers DROP CONSTRAINT IF EXISTS fk_voucher_promo;
ALTER TABLE IF EXISTS ONLY public.social_accounts DROP CONSTRAINT IF EXISTS fk_social_user;
ALTER TABLE IF EXISTS ONLY public.user_sessions DROP CONSTRAINT IF EXISTS fk_session_user;
ALTER TABLE IF EXISTS ONLY public.room_type_amenities DROP CONSTRAINT IF EXISTS fk_rta_rt;
ALTER TABLE IF EXISTS ONLY public.room_type_amenities DROP CONSTRAINT IF EXISTS fk_rta_amenity;
ALTER TABLE IF EXISTS ONLY public.room_types DROP CONSTRAINT IF EXISTS fk_rt_property;
ALTER TABLE IF EXISTS ONLY public.rate_plans DROP CONSTRAINT IF EXISTS fk_rp_rt;
ALTER TABLE IF EXISTS ONLY public.rooms DROP CONSTRAINT IF EXISTS fk_room_type;
ALTER TABLE IF EXISTS ONLY public.rooms DROP CONSTRAINT IF EXISTS fk_room_property;
ALTER TABLE IF EXISTS ONLY public.reviews DROP CONSTRAINT IF EXISTS fk_rev_prop;
ALTER TABLE IF EXISTS ONLY public.reviews DROP CONSTRAINT IF EXISTS fk_rev_mod;
ALTER TABLE IF EXISTS ONLY public.reviews DROP CONSTRAINT IF EXISTS fk_rev_cust;
ALTER TABLE IF EXISTS ONLY public.reviews DROP CONSTRAINT IF EXISTS fk_rev_booking;
ALTER TABLE IF EXISTS ONLY public.properties DROP CONSTRAINT IF EXISTS fk_property_reviewer;
ALTER TABLE IF EXISTS ONLY public.properties DROP CONSTRAINT IF EXISTS fk_property_partner;
ALTER TABLE IF EXISTS ONLY public.promotions DROP CONSTRAINT IF EXISTS fk_promo_partner;
ALTER TABLE IF EXISTS ONLY public.property_policies DROP CONSTRAINT IF EXISTS fk_policy_prop;
ALTER TABLE IF EXISTS ONLY public.property_media DROP CONSTRAINT IF EXISTS fk_pmedia_up;
ALTER TABLE IF EXISTS ONLY public.property_media DROP CONSTRAINT IF EXISTS fk_pmedia_rt;
ALTER TABLE IF EXISTS ONLY public.property_media DROP CONSTRAINT IF EXISTS fk_pmedia_prop;
ALTER TABLE IF EXISTS ONLY public.partner_profiles DROP CONSTRAINT IF EXISTS fk_partner_user;
ALTER TABLE IF EXISTS ONLY public.partner_profiles DROP CONSTRAINT IF EXISTS fk_partner_reviewer;
ALTER TABLE IF EXISTS ONLY public.property_amenities DROP CONSTRAINT IF EXISTS fk_pa_prop;
ALTER TABLE IF EXISTS ONLY public.property_amenities DROP CONSTRAINT IF EXISTS fk_pa_amenity;
ALTER TABLE IF EXISTS ONLY public.otp_tokens DROP CONSTRAINT IF EXISTS fk_otp_user;
ALTER TABLE IF EXISTS ONLY public.daily_rates DROP CONSTRAINT IF EXISTS fk_dr_rp;
ALTER TABLE IF EXISTS ONLY public.customer_profiles DROP CONSTRAINT IF EXISTS fk_customer_user;
ALTER TABLE IF EXISTS ONLY public.booking_rooms DROP CONSTRAINT IF EXISTS fk_br_rp;
ALTER TABLE IF EXISTS ONLY public.booking_rooms DROP CONSTRAINT IF EXISTS fk_br_room;
ALTER TABLE IF EXISTS ONLY public.booking_rooms DROP CONSTRAINT IF EXISTS fk_br_booking;
ALTER TABLE IF EXISTS ONLY public.bookings DROP CONSTRAINT IF EXISTS fk_booking_voucher;
ALTER TABLE IF EXISTS ONLY public.bookings DROP CONSTRAINT IF EXISTS fk_booking_rt;
ALTER TABLE IF EXISTS ONLY public.bookings DROP CONSTRAINT IF EXISTS fk_booking_rp;
ALTER TABLE IF EXISTS ONLY public.bookings DROP CONSTRAINT IF EXISTS fk_booking_prop;
ALTER TABLE IF EXISTS ONLY public.bookings DROP CONSTRAINT IF EXISTS fk_booking_cust;
ALTER TABLE IF EXISTS ONLY public.bookings DROP CONSTRAINT IF EXISTS fk_booking_canceler;
ALTER TABLE IF EXISTS ONLY public.booking_guests DROP CONSTRAINT IF EXISTS fk_bg_booking;
ALTER TABLE IF EXISTS ONLY public.audit_logs DROP CONSTRAINT IF EXISTS fk_audit_actor;
DROP INDEX IF EXISTS public.uq_voucher_code;
DROP INDEX IF EXISTS public.uq_users_uuid;
DROP INDEX IF EXISTS public.uq_users_phone;
DROP INDEX IF EXISTS public.uq_users_email;
DROP INDEX IF EXISTS public.uq_social_provider;
DROP INDEX IF EXISTS public.uq_session_token;
DROP INDEX IF EXISTS public.uq_room_property;
DROP INDEX IF EXISTS public.uq_rev_booking;
DROP INDEX IF EXISTS public.uq_property_slug;
DROP INDEX IF EXISTS public.uq_policy_prop;
DROP INDEX IF EXISTS public.uq_partner_user;
DROP INDEX IF EXISTS public.uq_daily_rate;
DROP INDEX IF EXISTS public.uq_customer_user;
DROP INDEX IF EXISTS public.uq_booking_code;
DROP INDEX IF EXISTS public.uq_amenity_name;
DROP INDEX IF EXISTS public.idx_users_type_status;
DROP INDEX IF EXISTS public.idx_users_status;
DROP INDEX IF EXISTS public.idx_session_active;
DROP INDEX IF EXISTS public.idx_review_property_status;
DROP INDEX IF EXISTS public.idx_review_customer;
DROP INDEX IF EXISTS public.idx_prop_search;
DROP INDEX IF EXISTS public.idx_prop_rating;
DROP INDEX IF EXISTS public.idx_prop_partner;
DROP INDEX IF EXISTS public.idx_prop_location;
DROP INDEX IF EXISTS public.idx_pmedia_prop;
DROP INDEX IF EXISTS public.idx_otp_lookup;
DROP INDEX IF EXISTS public.idx_daily_rate_plan_date;
DROP INDEX IF EXISTS public.idx_daily_rate_date_available;
DROP INDEX IF EXISTS public.idx_booking_property_dates;
DROP INDEX IF EXISTS public.idx_booking_property;
DROP INDEX IF EXISTS public.idx_booking_customer_status;
DROP INDEX IF EXISTS public.idx_booking_customer;
DROP INDEX IF EXISTS public.idx_bg_booking;
DROP INDEX IF EXISTS public.idx_audit_entity;
DROP INDEX IF EXISTS public.idx_audit_created;
DROP INDEX IF EXISTS public.idx_audit_actor;
ALTER TABLE IF EXISTS ONLY public.vouchers DROP CONSTRAINT IF EXISTS vouchers_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.user_sessions DROP CONSTRAINT IF EXISTS user_sessions_pkey;
ALTER TABLE IF EXISTS ONLY public.booking_rooms DROP CONSTRAINT IF EXISTS uq_br_booking_room;
ALTER TABLE IF EXISTS ONLY public.social_accounts DROP CONSTRAINT IF EXISTS social_accounts_pkey;
ALTER TABLE IF EXISTS ONLY public.rooms DROP CONSTRAINT IF EXISTS rooms_pkey;
ALTER TABLE IF EXISTS ONLY public.room_types DROP CONSTRAINT IF EXISTS room_types_pkey;
ALTER TABLE IF EXISTS ONLY public.room_type_amenities DROP CONSTRAINT IF EXISTS room_type_amenities_pkey;
ALTER TABLE IF EXISTS ONLY public.reviews DROP CONSTRAINT IF EXISTS reviews_pkey;
ALTER TABLE IF EXISTS ONLY public.rate_plans DROP CONSTRAINT IF EXISTS rate_plans_pkey;
ALTER TABLE IF EXISTS ONLY public.property_policies DROP CONSTRAINT IF EXISTS property_policies_pkey;
ALTER TABLE IF EXISTS ONLY public.property_media DROP CONSTRAINT IF EXISTS property_media_pkey;
ALTER TABLE IF EXISTS ONLY public.property_amenities DROP CONSTRAINT IF EXISTS property_amenities_pkey;
ALTER TABLE IF EXISTS ONLY public.properties DROP CONSTRAINT IF EXISTS properties_pkey;
ALTER TABLE IF EXISTS ONLY public.promotions DROP CONSTRAINT IF EXISTS promotions_pkey;
ALTER TABLE IF EXISTS ONLY public.partner_profiles DROP CONSTRAINT IF EXISTS partner_profiles_pkey;
ALTER TABLE IF EXISTS ONLY public.otp_tokens DROP CONSTRAINT IF EXISTS otp_tokens_pkey;
ALTER TABLE IF EXISTS ONLY public.legacy_source_rows DROP CONSTRAINT IF EXISTS legacy_source_rows_source_table_source_id_key;
ALTER TABLE IF EXISTS ONLY public.legacy_source_rows DROP CONSTRAINT IF EXISTS legacy_source_rows_pkey;
ALTER TABLE IF EXISTS ONLY public.daily_rates DROP CONSTRAINT IF EXISTS daily_rates_pkey;
ALTER TABLE IF EXISTS ONLY public.customer_profiles DROP CONSTRAINT IF EXISTS customer_profiles_pkey;
ALTER TABLE IF EXISTS ONLY public.bookings DROP CONSTRAINT IF EXISTS bookings_pkey;
ALTER TABLE IF EXISTS ONLY public.booking_rooms DROP CONSTRAINT IF EXISTS booking_rooms_pkey;
ALTER TABLE IF EXISTS ONLY public.booking_guests DROP CONSTRAINT IF EXISTS booking_guests_pkey;
ALTER TABLE IF EXISTS ONLY public.audit_logs DROP CONSTRAINT IF EXISTS audit_logs_pkey;
ALTER TABLE IF EXISTS ONLY public.amenities DROP CONSTRAINT IF EXISTS amenities_pkey;
ALTER TABLE IF EXISTS ONLY public._prisma_migrations DROP CONSTRAINT IF EXISTS _prisma_migrations_pkey;
ALTER TABLE IF EXISTS public.vouchers ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.user_sessions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.social_accounts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.rooms ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.room_types ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.reviews ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.rate_plans ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.property_policies ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.property_media ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.properties ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.promotions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.partner_profiles ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.otp_tokens ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.legacy_source_rows ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.daily_rates ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.customer_profiles ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.bookings ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.booking_guests ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.audit_logs ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.amenities ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.vouchers_id_seq;
DROP TABLE IF EXISTS public.vouchers;
DROP SEQUENCE IF EXISTS public.users_id_seq;
DROP TABLE IF EXISTS public.users;
DROP SEQUENCE IF EXISTS public.user_sessions_id_seq;
DROP TABLE IF EXISTS public.user_sessions;
DROP SEQUENCE IF EXISTS public.social_accounts_id_seq;
DROP TABLE IF EXISTS public.social_accounts;
DROP SEQUENCE IF EXISTS public.rooms_id_seq;
DROP TABLE IF EXISTS public.rooms;
DROP SEQUENCE IF EXISTS public.room_types_id_seq;
DROP TABLE IF EXISTS public.room_types;
DROP TABLE IF EXISTS public.room_type_amenities;
DROP SEQUENCE IF EXISTS public.reviews_id_seq;
DROP TABLE IF EXISTS public.reviews;
DROP SEQUENCE IF EXISTS public.rate_plans_id_seq;
DROP TABLE IF EXISTS public.rate_plans;
DROP SEQUENCE IF EXISTS public.property_policies_id_seq;
DROP TABLE IF EXISTS public.property_policies;
DROP SEQUENCE IF EXISTS public.property_media_id_seq;
DROP TABLE IF EXISTS public.property_media;
DROP TABLE IF EXISTS public.property_amenities;
DROP SEQUENCE IF EXISTS public.properties_id_seq;
DROP TABLE IF EXISTS public.properties;
DROP SEQUENCE IF EXISTS public.promotions_id_seq;
DROP TABLE IF EXISTS public.promotions;
DROP SEQUENCE IF EXISTS public.partner_profiles_id_seq;
DROP TABLE IF EXISTS public.partner_profiles;
DROP SEQUENCE IF EXISTS public.otp_tokens_id_seq;
DROP TABLE IF EXISTS public.otp_tokens;
DROP SEQUENCE IF EXISTS public.legacy_source_rows_id_seq;
DROP TABLE IF EXISTS public.legacy_source_rows;
DROP SEQUENCE IF EXISTS public.daily_rates_id_seq;
DROP TABLE IF EXISTS public.daily_rates;
DROP SEQUENCE IF EXISTS public.customer_profiles_id_seq;
DROP TABLE IF EXISTS public.customer_profiles;
DROP SEQUENCE IF EXISTS public.bookings_id_seq;
DROP TABLE IF EXISTS public.bookings;
DROP TABLE IF EXISTS public.booking_rooms;
DROP SEQUENCE IF EXISTS public.booking_guests_id_seq;
DROP TABLE IF EXISTS public.booking_guests;
DROP SEQUENCE IF EXISTS public.audit_logs_id_seq;
DROP TABLE IF EXISTS public.audit_logs;
DROP SEQUENCE IF EXISTS public.amenities_id_seq;
DROP TABLE IF EXISTS public.amenities;
DROP TABLE IF EXISTS public._prisma_migrations;
DROP TYPE IF EXISTS public.user_type_enum;
DROP TYPE IF EXISTS public.user_status_enum;
DROP TYPE IF EXISTS public.source_channel_enum;
DROP TYPE IF EXISTS public.social_provider_enum;
DROP TYPE IF EXISTS public.room_status_enum;
DROP TYPE IF EXISTS public.refund_status_enum;
DROP TYPE IF EXISTS public.property_type_enum;
DROP TYPE IF EXISTS public.property_status_enum;
DROP TYPE IF EXISTS public.promo_type_enum;
DROP TYPE IF EXISTS public.payment_status_enum;
DROP TYPE IF EXISTS public.payment_method_enum;
DROP TYPE IF EXISTS public.parking_type_enum;
DROP TYPE IF EXISTS public.otp_purpose_enum;
DROP TYPE IF EXISTS public.no_show_penalty_type_enum;
DROP TYPE IF EXISTS public.moderation_status_enum;
DROP TYPE IF EXISTS public.media_type_enum;
DROP TYPE IF EXISTS public.media_category_enum;
DROP TYPE IF EXISTS public.meal_plan_enum;
DROP TYPE IF EXISTS public.loyalty_tier_enum;
DROP TYPE IF EXISTS public.kyc_status_enum;
DROP TYPE IF EXISTS public.identifier_type_enum;
DROP TYPE IF EXISTS public.gender_enum;
DROP TYPE IF EXISTS public.fee_type_enum;
DROP TYPE IF EXISTS public.discount_type_enum;
DROP TYPE IF EXISTS public.device_type_enum;
DROP TYPE IF EXISTS public.charged_to_enum;
DROP TYPE IF EXISTS public.cancellation_type_enum;
DROP TYPE IF EXISTS public.business_type_enum;
DROP TYPE IF EXISTS public.booking_status_enum;
DROP SCHEMA IF EXISTS public;
--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: booking_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.booking_status_enum AS ENUM (
    'pending',
    'confirmed',
    'checked_in',
    'checked_out',
    'cancelled',
    'no_show'
);


--
-- Name: business_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.business_type_enum AS ENUM (
    'individual',
    'company'
);


--
-- Name: cancellation_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.cancellation_type_enum AS ENUM (
    'free',
    'flexible',
    'moderate',
    'strict',
    'non_refundable'
);


--
-- Name: charged_to_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.charged_to_enum AS ENUM (
    'customer',
    'partner'
);


--
-- Name: device_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.device_type_enum AS ENUM (
    'web',
    'ios',
    'android',
    'other'
);


--
-- Name: discount_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.discount_type_enum AS ENUM (
    'percent',
    'fixed'
);


--
-- Name: fee_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.fee_type_enum AS ENUM (
    'platform',
    'vat',
    'service',
    'other'
);


--
-- Name: gender_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.gender_enum AS ENUM (
    'male',
    'female',
    'other'
);


--
-- Name: identifier_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.identifier_type_enum AS ENUM (
    'email',
    'phone'
);


--
-- Name: kyc_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.kyc_status_enum AS ENUM (
    'pending',
    'approved',
    'rejected'
);


--
-- Name: loyalty_tier_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.loyalty_tier_enum AS ENUM (
    'member',
    'silver',
    'gold',
    'platinum'
);


--
-- Name: meal_plan_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.meal_plan_enum AS ENUM (
    'room_only',
    'breakfast',
    'half_board',
    'full_board',
    'all_inclusive'
);


--
-- Name: media_category_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.media_category_enum AS ENUM (
    'exterior',
    'interior',
    'room',
    'bathroom',
    'dining',
    'pool',
    'amenity',
    'other'
);


--
-- Name: media_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.media_type_enum AS ENUM (
    'image',
    'video',
    'virtual_tour'
);


--
-- Name: moderation_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.moderation_status_enum AS ENUM (
    'pending',
    'approved',
    'rejected'
);


--
-- Name: no_show_penalty_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.no_show_penalty_type_enum AS ENUM (
    'full_amount',
    'first_night',
    'percent'
);


--
-- Name: otp_purpose_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.otp_purpose_enum AS ENUM (
    'register',
    'login',
    'reset_password',
    'verify_phone',
    'verify_email'
);


--
-- Name: parking_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.parking_type_enum AS ENUM (
    'free',
    'paid',
    'none'
);


--
-- Name: payment_method_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.payment_method_enum AS ENUM (
    'credit_card',
    'debit_card',
    'ewallet',
    'bank_transfer',
    'pay_later',
    'loyalty_cash'
);


--
-- Name: payment_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.payment_status_enum AS ENUM (
    'unpaid',
    'partial',
    'paid',
    'refunded'
);


--
-- Name: promo_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.promo_type_enum AS ENUM (
    'early_bird',
    'last_minute',
    'long_stay',
    'flash_sale',
    'loyalty',
    'custom'
);


--
-- Name: property_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.property_status_enum AS ENUM (
    'draft',
    'pending_review',
    'active',
    'suspended',
    'rejected'
);


--
-- Name: property_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.property_type_enum AS ENUM (
    'hotel',
    'homestay',
    'resort',
    'apartment',
    'villa',
    'hostel'
);


--
-- Name: refund_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.refund_status_enum AS ENUM (
    'pending',
    'processing',
    'completed',
    'failed'
);


--
-- Name: room_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.room_status_enum AS ENUM (
    'available',
    'occupied',
    'blocked',
    'maintenance'
);


--
-- Name: social_provider_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.social_provider_enum AS ENUM (
    'google',
    'facebook',
    'apple',
    'zalo'
);


--
-- Name: source_channel_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.source_channel_enum AS ENUM (
    'web',
    'mobile',
    'ota',
    'direct'
);


--
-- Name: user_status_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_status_enum AS ENUM (
    'active',
    'suspended',
    'pending',
    'deleted'
);


--
-- Name: user_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_type_enum AS ENUM (
    'customer',
    'partner',
    'admin'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: _prisma_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public._prisma_migrations (
    id character varying(36) NOT NULL,
    checksum character varying(64) NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) NOT NULL,
    logs text,
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    applied_steps_count integer DEFAULT 0 NOT NULL
);


--
-- Name: amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.amenities (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    category character varying(50) NOT NULL,
    icon_code character varying(50),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: amenities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.amenities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: amenities_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.amenities_id_seq OWNED BY public.amenities.id;


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    actor_id bigint NOT NULL,
    action character varying(100) NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id bigint NOT NULL,
    old_values jsonb,
    new_values jsonb,
    ip_address character varying(45),
    user_agent text,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_logs_id_seq OWNED BY public.audit_logs.id;


--
-- Name: booking_guests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_guests (
    id bigint NOT NULL,
    booking_id bigint NOT NULL,
    full_name character varying(255) NOT NULL,
    id_card_number character varying(50),
    date_of_birth date,
    nationality character(2),
    is_primary boolean DEFAULT false NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: booking_guests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.booking_guests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: booking_guests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.booking_guests_id_seq OWNED BY public.booking_guests.id;


--
-- Name: booking_rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_rooms (
    id bigint NOT NULL,
    booking_id bigint NOT NULL,
    room_id bigint NOT NULL,
    rate_plan_id bigint NOT NULL,
    room_price numeric(12,2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: booking_rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id bigint NOT NULL,
    booking_code character varying(30) NOT NULL,
    customer_id bigint NOT NULL,
    property_id bigint NOT NULL,
    room_type_id bigint NOT NULL,
    rate_plan_id bigint NOT NULL,
    check_in_date date NOT NULL,
    check_out_date date NOT NULL,
    num_nights smallint NOT NULL,
    num_adults smallint DEFAULT 1 NOT NULL,
    num_children smallint DEFAULT 0 NOT NULL,
    subtotal_amount numeric(12,2) NOT NULL,
    discount_amount numeric(12,2) DEFAULT 0.00 NOT NULL,
    tax_amount numeric(12,2) DEFAULT 0.00 NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    platform_fee_amount numeric(12,2) DEFAULT 0.00 NOT NULL,
    partner_payout_amount numeric(12,2) DEFAULT 0.00 NOT NULL,
    currency character(3) DEFAULT 'VND'::bpchar NOT NULL,
    voucher_id bigint,
    loyalty_points_used integer DEFAULT 0 NOT NULL,
    status public.booking_status_enum DEFAULT 'pending'::public.booking_status_enum NOT NULL,
    payment_status public.payment_status_enum DEFAULT 'unpaid'::public.payment_status_enum NOT NULL,
    source_channel public.source_channel_enum DEFAULT 'web'::public.source_channel_enum NOT NULL,
    special_requests text,
    cancellation_reason text,
    cancelled_by bigint,
    cancelled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(6) without time zone
);


--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bookings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bookings_id_seq OWNED BY public.bookings.id;


--
-- Name: customer_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_profiles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    date_of_birth date,
    gender public.gender_enum,
    nationality character(2),
    id_card_number character varying(50),
    loyalty_tier public.loyalty_tier_enum DEFAULT 'member'::public.loyalty_tier_enum NOT NULL,
    loyalty_points_balance integer DEFAULT 0 NOT NULL,
    total_bookings integer DEFAULT 0 NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: customer_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.customer_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: customer_profiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.customer_profiles_id_seq OWNED BY public.customer_profiles.id;


--
-- Name: daily_rates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_rates (
    id bigint NOT NULL,
    rate_plan_id bigint NOT NULL,
    date date NOT NULL,
    price numeric(12,2) NOT NULL,
    available_qty integer NOT NULL,
    min_stay smallint DEFAULT 1 NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: daily_rates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.daily_rates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: daily_rates_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.daily_rates_id_seq OWNED BY public.daily_rates.id;


--
-- Name: legacy_source_rows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.legacy_source_rows (
    id bigint NOT NULL,
    source_table text NOT NULL,
    source_id text,
    payload jsonb NOT NULL,
    migrated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: legacy_source_rows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.legacy_source_rows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: legacy_source_rows_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.legacy_source_rows_id_seq OWNED BY public.legacy_source_rows.id;


--
-- Name: otp_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otp_tokens (
    id bigint NOT NULL,
    user_id bigint,
    identifier character varying(255) NOT NULL,
    identifier_type public.identifier_type_enum NOT NULL,
    purpose public.otp_purpose_enum NOT NULL,
    token_hash character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    used_at timestamp(6) without time zone,
    attempts smallint DEFAULT 0 NOT NULL,
    ip_address character varying(45),
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: otp_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.otp_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: otp_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.otp_tokens_id_seq OWNED BY public.otp_tokens.id;


--
-- Name: partner_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.partner_profiles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    business_name character varying(255) NOT NULL,
    business_type public.business_type_enum NOT NULL,
    tax_code character varying(50),
    id_card_number character varying(50),
    contract_url character varying(500),
    kyc_status public.kyc_status_enum DEFAULT 'pending'::public.kyc_status_enum NOT NULL,
    kyc_reviewed_by bigint,
    kyc_reviewed_at timestamp(6) without time zone,
    bank_account_name character varying(255),
    bank_account_number character varying(100),
    bank_name character varying(100),
    commission_tier character varying(50) DEFAULT 'standard'::character varying NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: partner_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.partner_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: partner_profiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.partner_profiles_id_seq OWNED BY public.partner_profiles.id;


--
-- Name: promotions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promotions (
    id bigint NOT NULL,
    partner_id bigint,
    name character varying(255) NOT NULL,
    promo_type public.promo_type_enum NOT NULL,
    discount_type public.discount_type_enum NOT NULL,
    discount_value numeric(12,2) NOT NULL,
    max_discount numeric(12,2),
    min_order_amount numeric(12,2) DEFAULT 0.00 NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    max_uses integer,
    total_used integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(6) without time zone
);


--
-- Name: promotions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.promotions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: promotions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.promotions_id_seq OWNED BY public.promotions.id;


--
-- Name: properties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.properties (
    id bigint NOT NULL,
    partner_id bigint NOT NULL,
    slug character varying(300) NOT NULL,
    name character varying(500) NOT NULL,
    property_type public.property_type_enum NOT NULL,
    description text,
    address text NOT NULL,
    city character varying(100) NOT NULL,
    district character varying(100),
    country_code character(2) DEFAULT 'VN'::bpchar NOT NULL,
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    star_rating smallint,
    avg_rating numeric(3,2) DEFAULT 0.00 NOT NULL,
    total_reviews integer DEFAULT 0 NOT NULL,
    check_in_time time(6) without time zone DEFAULT '14:00:00'::time without time zone NOT NULL,
    check_out_time time(6) without time zone DEFAULT '12:00:00'::time without time zone NOT NULL,
    status public.property_status_enum DEFAULT 'draft'::public.property_status_enum NOT NULL,
    reviewed_by bigint,
    reviewed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(6) without time zone,
    highlights jsonb,
    transport_connections jsonb,
    nearby_places jsonb
);


--
-- Name: properties_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: properties_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.properties_id_seq OWNED BY public.properties.id;


--
-- Name: property_amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_amenities (
    property_id bigint NOT NULL,
    amenity_id bigint NOT NULL
);


--
-- Name: property_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_media (
    id bigint NOT NULL,
    property_id bigint NOT NULL,
    room_type_id bigint,
    media_type public.media_type_enum DEFAULT 'image'::public.media_type_enum NOT NULL,
    category public.media_category_enum DEFAULT 'other'::public.media_category_enum NOT NULL,
    url character varying(500) NOT NULL,
    thumbnail_url character varying(500),
    caption character varying(500),
    is_cover boolean DEFAULT false NOT NULL,
    sort_order smallint DEFAULT 0 NOT NULL,
    uploaded_by bigint NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: property_media_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.property_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: property_media_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.property_media_id_seq OWNED BY public.property_media.id;


--
-- Name: property_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_policies (
    id bigint NOT NULL,
    property_id bigint NOT NULL,
    cancellation_type public.cancellation_type_enum DEFAULT 'flexible'::public.cancellation_type_enum NOT NULL,
    free_cancel_hours smallint,
    cancel_penalty_percent numeric(5,2) DEFAULT 0.00 NOT NULL,
    min_stay_nights smallint DEFAULT 1 NOT NULL,
    max_stay_nights smallint,
    check_in_from time(6) without time zone DEFAULT '14:00:00'::time without time zone NOT NULL,
    check_in_until time(6) without time zone DEFAULT '22:00:00'::time without time zone NOT NULL,
    check_out_from time(6) without time zone DEFAULT '00:00:00'::time without time zone,
    check_out_until time(6) without time zone DEFAULT '12:00:00'::time without time zone NOT NULL,
    early_check_in_allowed boolean DEFAULT false NOT NULL,
    early_check_in_fee numeric(12,2),
    late_check_out_allowed boolean DEFAULT false NOT NULL,
    late_check_out_fee numeric(12,2),
    pets_allowed boolean DEFAULT false NOT NULL,
    pet_fee numeric(12,2),
    pet_max_weight_kg numeric(5,2),
    smoking_allowed boolean DEFAULT false NOT NULL,
    smoking_penalty numeric(12,2),
    children_allowed boolean DEFAULT true NOT NULL,
    min_child_age smallint DEFAULT 0,
    infant_0_4_fee numeric(12,2) DEFAULT 0.00 NOT NULL,
    child_5_11_fee numeric(12,2) DEFAULT 0.00 NOT NULL,
    free_baby_cot boolean DEFAULT false NOT NULL,
    child_5_11_must_use_extra_bed boolean DEFAULT false NOT NULL,
    extra_bed_available boolean DEFAULT false NOT NULL,
    extra_bed_charge numeric(12,2),
    extra_person_fee numeric(12,2),
    no_show_penalty_type public.no_show_penalty_type_enum DEFAULT 'full_amount'::public.no_show_penalty_type_enum NOT NULL,
    no_show_penalty_value numeric(12,2),
    instant_confirmation boolean DEFAULT true NOT NULL,
    deposit_required boolean DEFAULT false NOT NULL,
    deposit_type public.discount_type_enum,
    deposit_value numeric(12,2),
    deposit_days_before smallint,
    accepted_payment_methods jsonb,
    wifi_fee numeric(12,2) DEFAULT 0.00 NOT NULL,
    breakfast_included boolean DEFAULT false NOT NULL,
    breakfast_fee numeric(12,2),
    airport_shuttle_available boolean DEFAULT false NOT NULL,
    airport_shuttle_fee numeric(12,2),
    parking_type public.parking_type_enum DEFAULT 'none'::public.parking_type_enum NOT NULL,
    parking_fee numeric(12,2),
    parties_allowed boolean DEFAULT false NOT NULL,
    quiet_hours_start time(6) without time zone,
    quiet_hours_end time(6) without time zone,
    requires_marriage_certificate boolean DEFAULT false NOT NULL,
    damage_deposit_required boolean DEFAULT false NOT NULL,
    damage_deposit_amount numeric(12,2),
    custom_rules text,
    liability_waiver text,
    force_majeure_policy text,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: property_policies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.property_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: property_policies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.property_policies_id_seq OWNED BY public.property_policies.id;


--
-- Name: rate_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rate_plans (
    id bigint NOT NULL,
    room_type_id bigint NOT NULL,
    name character varying(200) NOT NULL,
    meal_plan public.meal_plan_enum DEFAULT 'room_only'::public.meal_plan_enum NOT NULL,
    refundable boolean DEFAULT true NOT NULL,
    base_price numeric(12,2) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: rate_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rate_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rate_plans_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rate_plans_id_seq OWNED BY public.rate_plans.id;


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    booking_id bigint NOT NULL,
    property_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    overall_rating numeric(3,1) NOT NULL,
    cleanliness_rating numeric(3,1),
    service_rating numeric(3,1),
    location_rating numeric(3,1),
    value_rating numeric(3,1),
    title character varying(255),
    content text,
    moderation_status public.moderation_status_enum DEFAULT 'pending'::public.moderation_status_enum NOT NULL,
    moderated_by bigint,
    moderated_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(6) without time zone
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: reviews_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reviews_id_seq OWNED BY public.reviews.id;


--
-- Name: room_type_amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_type_amenities (
    room_type_id bigint NOT NULL,
    amenity_id bigint NOT NULL
);


--
-- Name: room_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_types (
    id bigint NOT NULL,
    property_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    area_sqm numeric(6,2),
    bed_configuration character varying(200),
    max_occupancy smallint DEFAULT 2 NOT NULL,
    view_type character varying(100),
    total_rooms integer DEFAULT 1 NOT NULL,
    base_price numeric(12,2) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(6) without time zone
);


--
-- Name: room_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.room_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: room_types_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.room_types_id_seq OWNED BY public.room_types.id;


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rooms (
    id bigint NOT NULL,
    room_type_id bigint NOT NULL,
    property_id bigint NOT NULL,
    room_number character varying(20) NOT NULL,
    floor smallint,
    status public.room_status_enum DEFAULT 'available'::public.room_status_enum NOT NULL,
    notes text,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rooms_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rooms_id_seq OWNED BY public.rooms.id;


--
-- Name: social_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.social_accounts (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider public.social_provider_enum NOT NULL,
    provider_id character varying(255) NOT NULL,
    access_token text,
    refresh_token text,
    token_expires_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: social_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.social_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: social_accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.social_accounts_id_seq OWNED BY public.social_accounts.id;


--
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sessions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(255) NOT NULL,
    device_name character varying(255),
    device_type public.device_type_enum DEFAULT 'web'::public.device_type_enum NOT NULL,
    ip_address character varying(45),
    user_agent text,
    last_active_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: user_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_sessions_id_seq OWNED BY public.user_sessions.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(20),
    password_hash character varying(255),
    full_name character varying(255) NOT NULL,
    avatar_url character varying(500),
    user_type public.user_type_enum NOT NULL,
    status public.user_status_enum DEFAULT 'pending'::public.user_status_enum NOT NULL,
    email_verified_at timestamp(6) without time zone,
    last_login_at timestamp(6) without time zone,
    preferred_language character(5) DEFAULT 'vi'::bpchar NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp(6) without time zone
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: vouchers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vouchers (
    id bigint NOT NULL,
    promotion_id bigint NOT NULL,
    code character varying(50) NOT NULL,
    max_uses_per_user smallint DEFAULT 1 NOT NULL,
    total_used integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: vouchers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.vouchers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: vouchers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.vouchers_id_seq OWNED BY public.vouchers.id;


--
-- Name: amenities id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.amenities ALTER COLUMN id SET DEFAULT nextval('public.amenities_id_seq'::regclass);


--
-- Name: audit_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs ALTER COLUMN id SET DEFAULT nextval('public.audit_logs_id_seq'::regclass);


--
-- Name: booking_guests id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_guests ALTER COLUMN id SET DEFAULT nextval('public.booking_guests_id_seq'::regclass);


--
-- Name: bookings id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings ALTER COLUMN id SET DEFAULT nextval('public.bookings_id_seq'::regclass);


--
-- Name: customer_profiles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_profiles ALTER COLUMN id SET DEFAULT nextval('public.customer_profiles_id_seq'::regclass);


--
-- Name: daily_rates id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_rates ALTER COLUMN id SET DEFAULT nextval('public.daily_rates_id_seq'::regclass);


--
-- Name: legacy_source_rows id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.legacy_source_rows ALTER COLUMN id SET DEFAULT nextval('public.legacy_source_rows_id_seq'::regclass);


--
-- Name: otp_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_tokens ALTER COLUMN id SET DEFAULT nextval('public.otp_tokens_id_seq'::regclass);


--
-- Name: partner_profiles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_profiles ALTER COLUMN id SET DEFAULT nextval('public.partner_profiles_id_seq'::regclass);


--
-- Name: promotions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotions ALTER COLUMN id SET DEFAULT nextval('public.promotions_id_seq'::regclass);


--
-- Name: properties id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties ALTER COLUMN id SET DEFAULT nextval('public.properties_id_seq'::regclass);


--
-- Name: property_media id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_media ALTER COLUMN id SET DEFAULT nextval('public.property_media_id_seq'::regclass);


--
-- Name: property_policies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_policies ALTER COLUMN id SET DEFAULT nextval('public.property_policies_id_seq'::regclass);


--
-- Name: rate_plans id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rate_plans ALTER COLUMN id SET DEFAULT nextval('public.rate_plans_id_seq'::regclass);


--
-- Name: reviews id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews ALTER COLUMN id SET DEFAULT nextval('public.reviews_id_seq'::regclass);


--
-- Name: room_types id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_types ALTER COLUMN id SET DEFAULT nextval('public.room_types_id_seq'::regclass);


--
-- Name: rooms id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms ALTER COLUMN id SET DEFAULT nextval('public.rooms_id_seq'::regclass);


--
-- Name: social_accounts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts ALTER COLUMN id SET DEFAULT nextval('public.social_accounts_id_seq'::regclass);


--
-- Name: user_sessions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions ALTER COLUMN id SET DEFAULT nextval('public.user_sessions_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: vouchers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vouchers ALTER COLUMN id SET DEFAULT nextval('public.vouchers_id_seq'::regclass);


--
-- Name: _prisma_migrations _prisma_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public._prisma_migrations
    ADD CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id);


--
-- Name: amenities amenities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.amenities
    ADD CONSTRAINT amenities_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: booking_guests booking_guests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_guests
    ADD CONSTRAINT booking_guests_pkey PRIMARY KEY (id);


--
-- Name: booking_rooms booking_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_rooms
    ADD CONSTRAINT booking_rooms_pkey PRIMARY KEY (id);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: customer_profiles customer_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_profiles
    ADD CONSTRAINT customer_profiles_pkey PRIMARY KEY (id);


--
-- Name: daily_rates daily_rates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_rates
    ADD CONSTRAINT daily_rates_pkey PRIMARY KEY (id);


--
-- Name: legacy_source_rows legacy_source_rows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.legacy_source_rows
    ADD CONSTRAINT legacy_source_rows_pkey PRIMARY KEY (id);


--
-- Name: legacy_source_rows legacy_source_rows_source_table_source_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.legacy_source_rows
    ADD CONSTRAINT legacy_source_rows_source_table_source_id_key UNIQUE (source_table, source_id);


--
-- Name: otp_tokens otp_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_tokens
    ADD CONSTRAINT otp_tokens_pkey PRIMARY KEY (id);


--
-- Name: partner_profiles partner_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_profiles
    ADD CONSTRAINT partner_profiles_pkey PRIMARY KEY (id);


--
-- Name: promotions promotions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT promotions_pkey PRIMARY KEY (id);


--
-- Name: properties properties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT properties_pkey PRIMARY KEY (id);


--
-- Name: property_amenities property_amenities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_amenities
    ADD CONSTRAINT property_amenities_pkey PRIMARY KEY (property_id, amenity_id);


--
-- Name: property_media property_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_media
    ADD CONSTRAINT property_media_pkey PRIMARY KEY (id);


--
-- Name: property_policies property_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_policies
    ADD CONSTRAINT property_policies_pkey PRIMARY KEY (id);


--
-- Name: rate_plans rate_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rate_plans
    ADD CONSTRAINT rate_plans_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: room_type_amenities room_type_amenities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_type_amenities
    ADD CONSTRAINT room_type_amenities_pkey PRIMARY KEY (room_type_id, amenity_id);


--
-- Name: room_types room_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_types
    ADD CONSTRAINT room_types_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: social_accounts social_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_pkey PRIMARY KEY (id);


--
-- Name: booking_rooms uq_br_booking_room; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_rooms
    ADD CONSTRAINT uq_br_booking_room UNIQUE (booking_id, room_id);


--
-- Name: user_sessions user_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vouchers vouchers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT vouchers_pkey PRIMARY KEY (id);


--
-- Name: idx_audit_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_actor ON public.audit_logs USING btree (actor_id);


--
-- Name: idx_audit_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_created ON public.audit_logs USING btree (created_at);


--
-- Name: idx_audit_entity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_entity ON public.audit_logs USING btree (entity_type, entity_id);


--
-- Name: idx_bg_booking; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bg_booking ON public.booking_guests USING btree (booking_id);


--
-- Name: idx_booking_customer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_booking_customer ON public.bookings USING btree (customer_id);


--
-- Name: idx_booking_customer_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_booking_customer_status ON public.bookings USING btree (customer_id, status);


--
-- Name: idx_booking_property; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_booking_property ON public.bookings USING btree (property_id);


--
-- Name: idx_booking_property_dates; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_booking_property_dates ON public.bookings USING btree (property_id, check_in_date, check_out_date);


--
-- Name: idx_daily_rate_date_available; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daily_rate_date_available ON public.daily_rates USING btree (date, available_qty);


--
-- Name: idx_daily_rate_plan_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_daily_rate_plan_date ON public.daily_rates USING btree (rate_plan_id, date);


--
-- Name: idx_otp_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_otp_lookup ON public.otp_tokens USING btree (identifier, purpose, expires_at);


--
-- Name: idx_pmedia_prop; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pmedia_prop ON public.property_media USING btree (property_id, category, sort_order);


--
-- Name: idx_prop_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prop_location ON public.properties USING btree (latitude, longitude);


--
-- Name: idx_prop_partner; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prop_partner ON public.properties USING btree (partner_id);


--
-- Name: idx_prop_rating; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prop_rating ON public.properties USING btree (status, avg_rating);


--
-- Name: idx_prop_search; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_prop_search ON public.properties USING btree (city, status, deleted_at);


--
-- Name: idx_review_customer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_review_customer ON public.reviews USING btree (customer_id);


--
-- Name: idx_review_property_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_review_property_status ON public.reviews USING btree (property_id, moderation_status, deleted_at);


--
-- Name: idx_session_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_active ON public.user_sessions USING btree (user_id, revoked_at, expires_at);


--
-- Name: idx_users_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_status ON public.users USING btree (status);


--
-- Name: idx_users_type_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_type_status ON public.users USING btree (user_type, status);


--
-- Name: uq_amenity_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_amenity_name ON public.amenities USING btree (name);


--
-- Name: uq_booking_code; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_booking_code ON public.bookings USING btree (booking_code);


--
-- Name: uq_customer_user; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_customer_user ON public.customer_profiles USING btree (user_id);


--
-- Name: uq_daily_rate; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_daily_rate ON public.daily_rates USING btree (rate_plan_id, date);


--
-- Name: uq_partner_user; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_partner_user ON public.partner_profiles USING btree (user_id);


--
-- Name: uq_policy_prop; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_policy_prop ON public.property_policies USING btree (property_id);


--
-- Name: uq_property_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_property_slug ON public.properties USING btree (slug);


--
-- Name: uq_rev_booking; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_rev_booking ON public.reviews USING btree (booking_id);


--
-- Name: uq_room_property; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_room_property ON public.rooms USING btree (property_id, room_number);


--
-- Name: uq_session_token; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_session_token ON public.user_sessions USING btree (token_hash);


--
-- Name: uq_social_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_social_provider ON public.social_accounts USING btree (provider, provider_id);


--
-- Name: uq_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_users_email ON public.users USING btree (email);


--
-- Name: uq_users_phone; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_users_phone ON public.users USING btree (phone);


--
-- Name: uq_users_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_users_uuid ON public.users USING btree (uuid);


--
-- Name: uq_voucher_code; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_voucher_code ON public.vouchers USING btree (code);


--
-- Name: audit_logs fk_audit_actor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: booking_guests fk_bg_booking; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_guests
    ADD CONSTRAINT fk_bg_booking FOREIGN KEY (booking_id) REFERENCES public.bookings(id);


--
-- Name: bookings fk_booking_canceler; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_booking_canceler FOREIGN KEY (cancelled_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: bookings fk_booking_cust; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_booking_cust FOREIGN KEY (customer_id) REFERENCES public.users(id);


--
-- Name: bookings fk_booking_prop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_booking_prop FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: bookings fk_booking_rp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_booking_rp FOREIGN KEY (rate_plan_id) REFERENCES public.rate_plans(id);


--
-- Name: bookings fk_booking_rt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_booking_rt FOREIGN KEY (room_type_id) REFERENCES public.room_types(id);


--
-- Name: bookings fk_booking_voucher; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk_booking_voucher FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);


--
-- Name: booking_rooms fk_br_booking; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_rooms
    ADD CONSTRAINT fk_br_booking FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE;


--
-- Name: booking_rooms fk_br_room; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_rooms
    ADD CONSTRAINT fk_br_room FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: booking_rooms fk_br_rp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_rooms
    ADD CONSTRAINT fk_br_rp FOREIGN KEY (rate_plan_id) REFERENCES public.rate_plans(id);


--
-- Name: customer_profiles fk_customer_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_profiles
    ADD CONSTRAINT fk_customer_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: daily_rates fk_dr_rp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_rates
    ADD CONSTRAINT fk_dr_rp FOREIGN KEY (rate_plan_id) REFERENCES public.rate_plans(id);


--
-- Name: otp_tokens fk_otp_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_tokens
    ADD CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: property_amenities fk_pa_amenity; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_amenities
    ADD CONSTRAINT fk_pa_amenity FOREIGN KEY (amenity_id) REFERENCES public.amenities(id) ON DELETE CASCADE;


--
-- Name: property_amenities fk_pa_prop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_amenities
    ADD CONSTRAINT fk_pa_prop FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE;


--
-- Name: partner_profiles fk_partner_reviewer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_profiles
    ADD CONSTRAINT fk_partner_reviewer FOREIGN KEY (kyc_reviewed_by) REFERENCES public.users(id);


--
-- Name: partner_profiles fk_partner_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.partner_profiles
    ADD CONSTRAINT fk_partner_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: property_media fk_pmedia_prop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_media
    ADD CONSTRAINT fk_pmedia_prop FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE;


--
-- Name: property_media fk_pmedia_rt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_media
    ADD CONSTRAINT fk_pmedia_rt FOREIGN KEY (room_type_id) REFERENCES public.room_types(id) ON DELETE CASCADE;


--
-- Name: property_media fk_pmedia_up; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_media
    ADD CONSTRAINT fk_pmedia_up FOREIGN KEY (uploaded_by) REFERENCES public.users(id);


--
-- Name: property_policies fk_policy_prop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_policies
    ADD CONSTRAINT fk_policy_prop FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: promotions fk_promo_partner; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT fk_promo_partner FOREIGN KEY (partner_id) REFERENCES public.partner_profiles(id);


--
-- Name: properties fk_property_partner; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT fk_property_partner FOREIGN KEY (partner_id) REFERENCES public.partner_profiles(id);


--
-- Name: properties fk_property_reviewer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT fk_property_reviewer FOREIGN KEY (reviewed_by) REFERENCES public.users(id);


--
-- Name: reviews fk_rev_booking; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_rev_booking FOREIGN KEY (booking_id) REFERENCES public.bookings(id);


--
-- Name: reviews fk_rev_cust; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_rev_cust FOREIGN KEY (customer_id) REFERENCES public.users(id);


--
-- Name: reviews fk_rev_mod; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_rev_mod FOREIGN KEY (moderated_by) REFERENCES public.users(id);


--
-- Name: reviews fk_rev_prop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk_rev_prop FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: rooms fk_room_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fk_room_property FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: rooms fk_room_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fk_room_type FOREIGN KEY (room_type_id) REFERENCES public.room_types(id);


--
-- Name: rate_plans fk_rp_rt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rate_plans
    ADD CONSTRAINT fk_rp_rt FOREIGN KEY (room_type_id) REFERENCES public.room_types(id);


--
-- Name: room_types fk_rt_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_types
    ADD CONSTRAINT fk_rt_property FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- Name: room_type_amenities fk_rta_amenity; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_type_amenities
    ADD CONSTRAINT fk_rta_amenity FOREIGN KEY (amenity_id) REFERENCES public.amenities(id);


--
-- Name: room_type_amenities fk_rta_rt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_type_amenities
    ADD CONSTRAINT fk_rta_rt FOREIGN KEY (room_type_id) REFERENCES public.room_types(id);


--
-- Name: user_sessions fk_session_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: social_accounts fk_social_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT fk_social_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: vouchers fk_voucher_promo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT fk_voucher_promo FOREIGN KEY (promotion_id) REFERENCES public.promotions(id);


--
-- PostgreSQL database dump complete
--

\unrestrict d6H5SbcSwpeaacMbynFBqKkH8HW8Se99obBevzkdi1TDOmCEfVJqObAPpaa4f22
