CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-- 1. Xóa Database cũ (nếu cần) và tạo mới
-- Lưu ý: Trong Postgres, lệnh CREATE DATABASE không thể chạy trong block giao dịch.
-- Bạn nên chạy lệnh này thủ công trước: CREATE DATABASE agoda_clone;
-- 2. Định nghĩa các kiểu ENUM (Postgres yêu cầu khai báo trước khi dùng trong bảng)
CREATE TYPE user_type_enum AS ENUM ('customer', 'partner', 'staff');
CREATE TYPE user_status_enum AS ENUM ('active', 'suspended', 'pending', 'deleted');
CREATE TYPE social_provider_enum AS ENUM ('google', 'facebook', 'apple', 'zalo');
CREATE TYPE business_type_enum AS ENUM ('individual', 'company');
CREATE TYPE kyc_status_enum AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE gender_enum AS ENUM ('male', 'female', 'other');
CREATE TYPE loyalty_tier_enum AS ENUM ('member', 'silver', 'gold', 'platinum');
CREATE TYPE identifier_type_enum AS ENUM ('email', 'phone');
CREATE TYPE otp_purpose_enum AS ENUM (
  'register',
  'login',
  'reset_password',
  'verify_phone',
  'verify_email'
);
CREATE TYPE device_type_enum AS ENUM ('web', 'ios', 'android', 'other');
-- 3. Bảng USERS
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  -- Dùng kiểu UUID chuẩn của Postgres
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  password_hash VARCHAR(255) DEFAULT NULL,
  full_name VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(500) DEFAULT NULL,
  user_type user_type_enum NOT NULL,
  status user_status_enum NOT NULL DEFAULT 'pending',
  email_verified_at TIMESTAMP DEFAULT NULL,
  last_login_at TIMESTAMP DEFAULT NULL,
  preferred_language CHAR(5) NOT NULL DEFAULT 'vi',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_users_uuid UNIQUE (uuid),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT uq_users_phone UNIQUE (phone),
  CONSTRAINT chk_email_not_empty CHECK (email <> ''),
  CONSTRAINT chk_phone_format CHECK (
    phone IS NULL
    OR phone <> ''
  )
);
-- Index cho hiệu năng
CREATE INDEX idx_users_type_status ON users (user_type, status);
CREATE INDEX idx_users_status ON users (status);
-- 4. Bảng SOCIAL_ACCOUNTS
CREATE TABLE social_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  provider social_provider_enum NOT NULL,
  provider_id VARCHAR(255) NOT NULL,
  access_token TEXT DEFAULT NULL,
  refresh_token TEXT DEFAULT NULL,
  token_expires_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_social_provider UNIQUE (provider, provider_id),
  CONSTRAINT fk_social_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);
-- 5. Bảng PARTNER_PROFILES
CREATE TABLE partner_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  business_name VARCHAR(255) NOT NULL,
  business_type business_type_enum NOT NULL,
  tax_code VARCHAR(50) DEFAULT NULL,
  id_card_number VARCHAR(50) DEFAULT NULL,
  contract_url VARCHAR(500) DEFAULT NULL,
  kyc_status kyc_status_enum NOT NULL DEFAULT 'pending',
  kyc_reviewed_by BIGINT DEFAULT NULL,
  kyc_reviewed_at TIMESTAMP DEFAULT NULL,
  bank_account_name VARCHAR(255) DEFAULT NULL,
  bank_account_number VARCHAR(100) DEFAULT NULL,
  bank_name VARCHAR(100) DEFAULT NULL,
  commission_tier VARCHAR(50) NOT NULL DEFAULT 'standard',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_partner_user UNIQUE (user_id),
  CONSTRAINT fk_partner_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_partner_reviewer FOREIGN KEY (kyc_reviewed_by) REFERENCES users (id) ON DELETE
  SET NULL
);
-- 6. Bảng CUSTOMER_PROFILES
CREATE TABLE customer_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  date_of_birth DATE DEFAULT NULL,
  gender gender_enum DEFAULT NULL,
  nationality CHAR(2) DEFAULT NULL,
  id_card_number VARCHAR(50) DEFAULT NULL,
  loyalty_tier loyalty_tier_enum NOT NULL DEFAULT 'member',
  loyalty_points_balance INT NOT NULL DEFAULT 0,
  total_bookings INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_customer_user UNIQUE (user_id),
  CONSTRAINT fk_customer_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);
CREATE TABLE otp_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT DEFAULT NULL,
  identifier VARCHAR(255) NOT NULL,
  identifier_type identifier_type_enum NOT NULL,
  purpose otp_purpose_enum NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP DEFAULT NULL,
  attempts SMALLINT NOT NULL DEFAULT 0,
  ip_address VARCHAR(45) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE
  SET NULL
);
CREATE INDEX idx_otp_lookup ON otp_tokens (identifier, purpose, expires_at);
CREATE TABLE user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  device_name VARCHAR(255) DEFAULT NULL,
  device_type device_type_enum NOT NULL DEFAULT 'web',
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  last_active_at TIMESTAMP DEFAULT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_session_token UNIQUE (token_hash),
  CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_session_active ON user_sessions (user_id, revoked_at, expires_at);
-- 1. Định nghĩa các kiểu ENUM mới cho Property và Room
CREATE TYPE property_type_enum AS ENUM (
  'hotel',
  'homestay',
  'resort',
  'apartment',
  'villa',
  'hostel'
);
CREATE TYPE property_status_enum AS ENUM ('draft', 'pending_review', 'active', 'suspended');
CREATE TYPE room_status_enum AS ENUM (
  'available',
  'occupied',
  'blocked',
  'maintenance'
);
CREATE TYPE media_type_enum AS ENUM ('image', 'video', 'virtual_tour');
CREATE TYPE media_category_enum AS ENUM (
  'exterior',
  'interior',
  'room',
  'bathroom',
  'dining',
  'pool',
  'amenity',
  'other'
);
-- 2. Bảng PROPERTIES
CREATE TABLE properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id BIGINT NOT NULL,
  slug VARCHAR(300) NOT NULL,
  name VARCHAR(500) NOT NULL,
  property_type property_type_enum NOT NULL,
  description TEXT DEFAULT NULL,
  address TEXT NOT NULL,
  city VARCHAR(100) NOT NULL,
  district VARCHAR(100) DEFAULT NULL,
  country_code CHAR(2) NOT NULL DEFAULT 'VN',
  latitude DECIMAL(10, 8) NOT NULL,
  longitude DECIMAL(11, 8) NOT NULL,
  star_rating SMALLINT DEFAULT NULL,
  -- Postgres dùng SMALLINT thay cho TINYINT
  avg_rating DECIMAL(3, 2) NOT NULL DEFAULT 0.00,
  total_reviews INT NOT NULL DEFAULT 0,
  check_in_time TIME NOT NULL DEFAULT '14:00:00',
  check_out_time TIME NOT NULL DEFAULT '12:00:00',
  status property_status_enum NOT NULL DEFAULT 'draft',
  reviewed_by BIGINT DEFAULT NULL,
  reviewed_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_property_slug UNIQUE (slug),
  CONSTRAINT fk_property_partner FOREIGN KEY (partner_id) REFERENCES partner_profiles (id),
  CONSTRAINT fk_property_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE
  SET NULL,
    CONSTRAINT chk_star_rating CHECK (
      star_rating BETWEEN 1 AND 5
    )
);
-- Index cho Properties
CREATE INDEX idx_prop_partner ON properties (partner_id);
CREATE INDEX idx_prop_search ON properties (city, status);
CREATE INDEX idx_prop_rating ON properties (status, avg_rating);
CREATE INDEX idx_prop_location ON properties (latitude, longitude);
-- 3. Bảng ROOM_TYPES
CREATE TABLE room_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  area_sqm DECIMAL(6, 2) DEFAULT NULL,
  bed_configuration VARCHAR(200) DEFAULT NULL,
  max_occupancy SMALLINT NOT NULL DEFAULT 2,
  view_type VARCHAR(100) DEFAULT NULL,
  total_rooms INT NOT NULL DEFAULT 1,
  base_price DECIMAL(12, 2) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rt_property FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE
);
-- 4. Bảng ROOMS
CREATE TABLE rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_type_id BIGINT NOT NULL,
  property_id BIGINT NOT NULL,
  room_number VARCHAR(20) NOT NULL,
  floor SMALLINT DEFAULT NULL,
  status room_status_enum NOT NULL DEFAULT 'available',
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_room_property UNIQUE (property_id, room_number),
  CONSTRAINT fk_room_type FOREIGN KEY (room_type_id) REFERENCES room_types (id) ON DELETE CASCADE,
  CONSTRAINT fk_room_property FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE
);
-- 5. Bảng AMENITIES (Tiện nghi)
CREATE TABLE amenities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  category VARCHAR(50) NOT NULL,
  icon_code VARCHAR(50) DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_amenity_name UNIQUE (name)
);
-- 6. Bảng trung gian Property-Amenity
CREATE TABLE property_amenities (
  property_id BIGINT NOT NULL,
  amenity_id BIGINT NOT NULL,
  PRIMARY KEY (property_id, amenity_id),
  CONSTRAINT fk_pa_prop FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE,
  CONSTRAINT fk_pa_amenity FOREIGN KEY (amenity_id) REFERENCES amenities (id) ON DELETE CASCADE
);
-- 7. Bảng trung gian RoomType-Amenity
CREATE TABLE room_type_amenities (
  room_type_id BIGINT NOT NULL,
  amenity_id BIGINT NOT NULL,
  PRIMARY KEY (room_type_id, amenity_id),
  CONSTRAINT fk_rta_rt FOREIGN KEY (room_type_id) REFERENCES room_types (id) ON DELETE CASCADE,
  CONSTRAINT fk_rta_amenity FOREIGN KEY (amenity_id) REFERENCES amenities (id) ON DELETE CASCADE
);
-- 8. Bảng PROPERTY_MEDIA
CREATE TABLE property_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT NOT NULL,
  room_type_id BIGINT DEFAULT NULL,
  media_type media_type_enum NOT NULL DEFAULT 'image',
  category media_category_enum NOT NULL DEFAULT 'other',
  url VARCHAR(500) NOT NULL,
  thumbnail_url VARCHAR(500) DEFAULT NULL,
  caption VARCHAR(500) DEFAULT NULL,
  is_cover BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order SMALLINT NOT NULL DEFAULT 0,
  uploaded_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pmedia_prop FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE,
  CONSTRAINT fk_pmedia_rt FOREIGN KEY (room_type_id) REFERENCES room_types (id) ON DELETE CASCADE,
  CONSTRAINT fk_pmedia_up FOREIGN KEY (uploaded_by) REFERENCES users (id)
);
CREATE INDEX idx_pmedia_prop ON property_media (property_id, category, sort_order);
-- 1. Định nghĩa các kiểu ENUM cho Policies và Promotions
CREATE TYPE cancellation_type_enum AS ENUM (
  'free',
  'flexible',
  'moderate',
  'strict',
  'non_refundable'
);
CREATE TYPE meal_plan_enum AS ENUM (
  'room_only',
  'breakfast',
  'half_board',
  'full_board',
  'all_inclusive'
);
CREATE TYPE promo_type_enum AS ENUM (
  'early_bird',
  'last_minute',
  'long_stay',
  'flash_sale',
  'loyalty',
  'custom'
);
CREATE TYPE discount_type_enum AS ENUM ('percent', 'fixed');
CREATE TYPE no_show_penalty_type_enum AS ENUM ('full_amount', 'first_night', 'percent');
CREATE TYPE parking_type_enum AS ENUM ('free', 'paid', 'none');
-- 2. Bảng PROPERTY_POLICIES (Đã gộp các cột ALTER từ file gốc)
CREATE TABLE property_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT NOT NULL,
  cancellation_type cancellation_type_enum NOT NULL DEFAULT 'flexible',
  free_cancel_hours SMALLINT DEFAULT NULL,
  cancel_penalty_percent DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
  min_stay_nights SMALLINT NOT NULL DEFAULT 1,
  max_stay_nights SMALLINT DEFAULT NULL,
  check_in_from TIME NOT NULL DEFAULT '14:00:00',
  check_in_until TIME NOT NULL DEFAULT '22:00:00',
  check_out_from TIME DEFAULT '00:00:00',
  check_out_until TIME NOT NULL DEFAULT '12:00:00',
  early_check_in_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  early_check_in_fee DECIMAL(12, 2) DEFAULT NULL,
  late_check_out_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  late_check_out_fee DECIMAL(12, 2) DEFAULT NULL,
  pets_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  pet_fee DECIMAL(12, 2) DEFAULT NULL,
  pet_max_weight_kg DECIMAL(5, 2) DEFAULT NULL,
  smoking_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  smoking_penalty DECIMAL(12, 2) DEFAULT NULL,
  children_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  min_child_age SMALLINT DEFAULT 0,
  infant_0_4_fee DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  child_5_11_fee DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  free_baby_cot BOOLEAN NOT NULL DEFAULT FALSE,
  child_5_11_must_use_extra_bed BOOLEAN NOT NULL DEFAULT FALSE,
  extra_bed_available BOOLEAN NOT NULL DEFAULT FALSE,
  extra_bed_charge DECIMAL(12, 2) DEFAULT NULL,
  extra_person_fee DECIMAL(12, 2) DEFAULT NULL,
  no_show_penalty_type no_show_penalty_type_enum NOT NULL DEFAULT 'full_amount',
  no_show_penalty_value DECIMAL(12, 2) DEFAULT NULL,
  instant_confirmation BOOLEAN NOT NULL DEFAULT TRUE,
  deposit_required BOOLEAN NOT NULL DEFAULT FALSE,
  deposit_type discount_type_enum DEFAULT NULL,
  deposit_value DECIMAL(12, 2) DEFAULT NULL,
  deposit_days_before SMALLINT DEFAULT NULL,
  accepted_payment_methods JSONB DEFAULT NULL,
  -- Dùng JSONB cho mảng phương thức
  wifi_fee DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  breakfast_included BOOLEAN NOT NULL DEFAULT FALSE,
  breakfast_fee DECIMAL(12, 2) DEFAULT NULL,
  airport_shuttle_available BOOLEAN NOT NULL DEFAULT FALSE,
  airport_shuttle_fee DECIMAL(12, 2) DEFAULT NULL,
  parking_type parking_type_enum NOT NULL DEFAULT 'none',
  parking_fee DECIMAL(12, 2) DEFAULT NULL,
  parties_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  quiet_hours_start TIME DEFAULT NULL,
  quiet_hours_end TIME DEFAULT NULL,
  requires_marriage_certificate BOOLEAN NOT NULL DEFAULT FALSE,
  damage_deposit_required BOOLEAN NOT NULL DEFAULT FALSE,
  damage_deposit_amount DECIMAL(12, 2) DEFAULT NULL,
  custom_rules TEXT DEFAULT NULL,
  liability_waiver TEXT DEFAULT NULL,
  force_majeure_policy TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_policy_prop UNIQUE (property_id),
  CONSTRAINT fk_policy_prop FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE
);
-- 3. Bảng RATE_PLANS
CREATE TABLE rate_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_type_id BIGINT NOT NULL,
  name VARCHAR(200) NOT NULL,
  meal_plan meal_plan_enum NOT NULL DEFAULT 'room_only',
  refundable BOOLEAN NOT NULL DEFAULT TRUE,
  base_price DECIMAL(12, 2) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rp_rt FOREIGN KEY (room_type_id) REFERENCES room_types (id) ON DELETE CASCADE
);
-- 4. Bảng DAILY_RATES
CREATE TABLE daily_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rate_plan_id BIGINT NOT NULL,
  date DATE NOT NULL,
  price DECIMAL(12, 2) NOT NULL,
  available_qty INT NOT NULL,
  min_stay SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_daily_rate UNIQUE (rate_plan_id, date),
  CONSTRAINT fk_dr_rp FOREIGN KEY (rate_plan_id) REFERENCES rate_plans (id) ON DELETE CASCADE,
  CONSTRAINT chk_daily_rate_price CHECK (price >= 0)
);
-- 5. Bảng PROMOTIONS
CREATE TABLE promotions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id BIGINT DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  promo_type promo_type_enum NOT NULL,
  discount_type discount_type_enum NOT NULL,
  discount_value DECIMAL(10, 2) NOT NULL,
  max_discount DECIMAL(12, 2) DEFAULT NULL,
  min_order_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  max_uses INT DEFAULT NULL,
  total_used INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_promo_partner FOREIGN KEY (partner_id) REFERENCES partner_profiles (id) ON DELETE
  SET NULL
);
-- 6. Bảng VOUCHERS
CREATE TABLE vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promotion_id BIGINT NOT NULL,
  code VARCHAR(50) NOT NULL,
  max_uses_per_user SMALLINT NOT NULL DEFAULT 1,
  total_used INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_voucher_code UNIQUE (code),
  CONSTRAINT fk_voucher_promo FOREIGN KEY (promotion_id) REFERENCES promotions (id) ON DELETE CASCADE
);
-- 1. Định nghĩa các kiểu ENUM cho Booking và Payment
CREATE TYPE booking_status_enum AS ENUM (
  'pending',
  'confirmed',
  'checked_in',
  'checked_out',
  'cancelled',
  'no_show'
);
CREATE TYPE payment_status_enum AS ENUM ('unpaid', 'partial', 'paid', 'refunded');
CREATE TYPE source_channel_enum AS ENUM ('web', 'mobile', 'ota', 'direct');
CREATE TYPE fee_type_enum AS ENUM ('platform', 'vat', 'service', 'other');
CREATE TYPE charged_to_enum AS ENUM ('customer', 'partner');
CREATE TYPE payment_method_enum AS ENUM (
  'credit_card',
  'debit_card',
  'ewallet',
  'bank_transfer',
  'pay_later',
  'loyalty_cash'
);
CREATE TYPE refund_status_enum AS ENUM ('pending', 'processing', 'completed', 'failed');
CREATE TYPE moderation_status_enum AS ENUM ('pending', 'approved', 'rejected');
-- 2. Bảng BOOKINGS
CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code VARCHAR(30) NOT NULL,
  customer_id BIGINT NOT NULL,
  property_id BIGINT NOT NULL,
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  num_nights SMALLINT NOT NULL,
  num_adults SMALLINT NOT NULL DEFAULT 1,
  num_children SMALLINT NOT NULL DEFAULT 0,
  subtotal_amount DECIMAL(12, 2) NOT NULL,
  discount_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  tax_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(12, 2) NOT NULL,
  platform_fee_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  partner_payout_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  voucher_id BIGINT DEFAULT NULL,
  loyalty_points_used INT NOT NULL DEFAULT 0,
  status booking_status_enum NOT NULL DEFAULT 'pending',
  payment_status payment_status_enum NOT NULL DEFAULT 'unpaid',
  source_channel source_channel_enum NOT NULL DEFAULT 'web',
  special_requests TEXT DEFAULT NULL,
  cancellation_reason TEXT DEFAULT NULL,
  cancelled_by BIGINT DEFAULT NULL,
  cancelled_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_booking_code UNIQUE (booking_code),
  CONSTRAINT fk_booking_cust FOREIGN KEY (customer_id) REFERENCES users (id),
  CONSTRAINT fk_booking_prop FOREIGN KEY (property_id) REFERENCES properties (id),
  CONSTRAINT fk_booking_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers (id) ON DELETE
  SET NULL,
    CONSTRAINT fk_booking_canceler FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE
  SET NULL,
    CONSTRAINT chk_booking_dates CHECK (check_in_date < check_out_date),
    -- Postgres trừ 2 date ra integer:
    CONSTRAINT chk_booking_nights CHECK (num_nights = (check_out_date - check_in_date)),
    CONSTRAINT chk_booking_total CHECK (total_amount >= 0)
);
CREATE INDEX idx_booking_customer ON bookings (customer_id);
CREATE INDEX idx_booking_property ON bookings (property_id);
-- 12. Bổ sung các bảng thiếu để khớp với Trigger
CREATE TABLE booking_guests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  id_card_number VARCHAR(50) DEFAULT NULL,
  date_of_birth DATE DEFAULT NULL,
  nationality CHAR(2) DEFAULT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bg_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE
);
CREATE INDEX idx_bg_booking ON booking_guests (booking_id);
CREATE TABLE review_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT NOT NULL,
  responder_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_rr_review UNIQUE (review_id),
  CONSTRAINT fk_rr_rev FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE,
  CONSTRAINT fk_rr_resp FOREIGN KEY (responder_id) REFERENCES users (id)
);
CREATE TABLE payout_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  status payout_status_enum NOT NULL DEFAULT 'pending',
  reviewed_by BIGINT DEFAULT NULL,
  reviewed_at TIMESTAMP DEFAULT NULL,
  note TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pr_wal FOREIGN KEY (wallet_id) REFERENCES payout_wallets (id),
  CONSTRAINT fk_pr_rev FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE
  SET NULL
);
-- 1. Bảng VOUCHER_USAGES (Chi tiết sử dụng voucher)
-- Lưu ý: Đã có ở trên nhưng nếu TablePlus báo thiếu thì check lại quan hệ
CREATE TABLE IF NOT EXISTS voucher_usages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  voucher_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  booking_id BIGINT NOT NULL,
  discount_applied DECIMAL(12, 2) NOT NULL,
  used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_vu_voucher_booking UNIQUE (voucher_id, booking_id),
  CONSTRAINT fk_vu_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers (id) ON DELETE CASCADE,
  CONSTRAINT fk_vu_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
-- 2. Bảng BOOKING_FEES (Chi tiết các loại phí của đơn đặt)
CREATE TABLE booking_fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL,
  fee_config_id BIGINT DEFAULT NULL,
  fee_name VARCHAR(200) NOT NULL,
  fee_type fee_type_enum NOT NULL,
  rate_snapshot DECIMAL(8, 4) DEFAULT NULL,
  base_amount DECIMAL(12, 2) NOT NULL,
  fee_amount DECIMAL(12, 2) NOT NULL,
  charged_to charged_to_enum NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bf_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE
);
-- 3. Bảng REVIEW_MEDIA (Ảnh/Video đính kèm đánh giá)
CREATE TABLE review_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT NOT NULL,
  media_type media_type_enum NOT NULL DEFAULT 'image',
  url VARCHAR(500) NOT NULL,
  thumbnail_url VARCHAR(500) DEFAULT NULL,
  sort_order SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rm_review FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE
);
-- 4. Bảng LOYALTY_POINT_LEDGER (Lịch sử điểm thưởng)
CREATE TABLE loyalty_point_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type VARCHAR(20) NOT NULL,
  -- earn, redeem, expire, adjust
  points INT NOT NULL,
  balance_after INT NOT NULL,
  ref_type VARCHAR(50) DEFAULT NULL,
  ref_id BIGINT DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  expires_at DATE DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lpl_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
-- 5. Bảng WISHLISTS (Danh sách yêu thích)
CREATE TABLE wishlists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  property_id BIGINT NOT NULL,
  note VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_wl_user_prop UNIQUE (user_id, property_id),
  CONSTRAINT fk_wl_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_wl_prop FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE
);
-- 6. Bảng RISK_RULES (Quy tắc rủi ro/gian lận)
CREATE TABLE risk_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_code VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  risk_weight DECIMAL(5, 2) NOT NULL DEFAULT 10.00,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_risk_rule_code UNIQUE (rule_code)
);
-- 7. Bảng RISK_ASSESSMENTS (Đánh giá rủi ro thanh toán)
CREATE TABLE risk_assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT NOT NULL,
  booking_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  risk_score DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
  decision VARCHAR(20) NOT NULL DEFAULT 'flagged',
  -- approve, review, reject
  triggered_rules JSONB DEFAULT NULL,
  reviewed_by BIGINT DEFAULT NULL,
  reviewed_at TIMESTAMP DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_risk_pay UNIQUE (payment_id),
  CONSTRAINT fk_risk_pay FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE CASCADE,
  CONSTRAINT fk_risk_book FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
  CONSTRAINT fk_risk_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_risk_rev FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE
  SET NULL
);
CREATE TABLE system_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key VARCHAR(200) NOT NULL,
  config_value TEXT NOT NULL,
  value_type config_value_type_enum NOT NULL DEFAULT 'string',
  group_name VARCHAR(100) NOT NULL,
  description TEXT DEFAULT NULL,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  updated_by BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_syscfg_key UNIQUE (config_key)
);
CREATE TABLE user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  scope_type VARCHAR(50) DEFAULT NULL,
  scope_value VARCHAR(100) DEFAULT NULL,
  granted_by BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_ur_scope UNIQUE (user_id, role_id, scope_type, scope_value),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
  CONSTRAINT fk_ur_grant FOREIGN KEY (granted_by) REFERENCES users (id) ON DELETE
  SET NULL
);
-- 3. Bảng BOOKING_ROOMS (Chi tiết phòng trong đơn đặt)
CREATE TABLE booking_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  rate_plan_id BIGINT NOT NULL,
  room_price DECIMAL(12, 2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_br_booking_room UNIQUE (booking_id, room_id),
  CONSTRAINT fk_br_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
  CONSTRAINT fk_br_room FOREIGN KEY (room_id) REFERENCES rooms (id),
  CONSTRAINT fk_br_rp FOREIGN KEY (rate_plan_id) REFERENCES rate_plans (id)
);
-- 4. Bảng PAYMENTS
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL,
  transaction_ref VARCHAR(100) NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  payment_method payment_method_enum NOT NULL,
  gateway VARCHAR(50) NOT NULL,
  gateway_response JSONB DEFAULT NULL,
  status refund_status_enum NOT NULL DEFAULT 'pending',
  -- Reused Enum or separate
  paid_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_pay_ref UNIQUE (transaction_ref),
  CONSTRAINT fk_pay_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
  CONSTRAINT chk_payment_amount CHECK (amount > 0)
);
CREATE INDEX idx_pay_status_method ON payments (status, payment_method);
CREATE INDEX idx_pay_created ON payments (created_at);
-- 5. Bảng REVIEWS
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL,
  property_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  overall_rating DECIMAL(3, 1) NOT NULL,
  cleanliness_rating DECIMAL(3, 1) DEFAULT NULL,
  service_rating DECIMAL(3, 1) DEFAULT NULL,
  location_rating DECIMAL(3, 1) DEFAULT NULL,
  value_rating DECIMAL(3, 1) DEFAULT NULL,
  title VARCHAR(255) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  moderation_status moderation_status_enum NOT NULL DEFAULT 'pending',
  moderated_by BIGINT DEFAULT NULL,
  moderated_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_rev_booking UNIQUE (booking_id),
  CONSTRAINT fk_rev_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
  CONSTRAINT fk_rev_prop FOREIGN KEY (property_id) REFERENCES properties (id),
  CONSTRAINT fk_rev_cust FOREIGN KEY (customer_id) REFERENCES users (id),
  CONSTRAINT fk_rev_mod FOREIGN KEY (moderated_by) REFERENCES users (id) ON DELETE
  SET NULL
);
CREATE INDEX idx_vu_user_voucher ON voucher_usages (user_id, voucher_id);
CREATE INDEX idx_vu_booking ON voucher_usages (booking_id);
-- 1. Định nghĩa các kiểu ENUM cho Tài chính và Support
CREATE TYPE wallet_tx_type_enum AS ENUM ('credit', 'debit');
CREATE TYPE payout_status_enum AS ENUM (
  'pending',
  'approved',
  'rejected',
  'processing',
  'completed'
);
CREATE TYPE commission_scope_enum AS ENUM (
  'global',
  'partner_tier',
  'partner',
  'property_type',
  'country'
);
CREATE TYPE ticket_category_enum AS ENUM (
  'booking_issue',
  'payment',
  'property',
  'account',
  'other'
);
CREATE TYPE ticket_status_enum AS ENUM (
  'open',
  'in_progress',
  'pending_customer',
  'resolved',
  'closed'
);
CREATE TYPE priority_enum AS ENUM ('low', 'medium', 'high', 'urgent');
CREATE TYPE department_enum AS ENUM (
  'engineering',
  'customer_service',
  'finance',
  'operations',
  'marketing',
  'management'
);
CREATE TYPE config_value_type_enum AS ENUM (
  'string',
  'integer',
  'decimal',
  'boolean',
  'json'
);
-- 2. Bảng PAYOUT_WALLETS & TRANSACTIONS
CREATE TABLE payout_wallets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id BIGINT NOT NULL,
  available_balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  pending_balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  total_earned DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  total_withdrawn DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  currency CHAR(3) NOT NULL DEFAULT 'VND',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_wal_partner UNIQUE (partner_id),
  CONSTRAINT fk_wal_partner FOREIGN KEY (partner_id) REFERENCES partner_profiles (id)
);
CREATE TABLE wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT NOT NULL,
  type wallet_tx_type_enum NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  balance_after DECIMAL(15, 2) NOT NULL,
  description VARCHAR(500) NOT NULL,
  ref_type VARCHAR(50) DEFAULT NULL,
  ref_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_wt_wal FOREIGN KEY (wallet_id) REFERENCES payout_wallets (id) ON DELETE CASCADE
);
-- 3. Bảng SUPPORT_TICKETS & MESSAGES
CREATE TABLE support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_code VARCHAR(30) NOT NULL,
  requester_id BIGINT NOT NULL,
  booking_id BIGINT DEFAULT NULL,
  category ticket_category_enum NOT NULL,
  subject VARCHAR(500) NOT NULL,
  status ticket_status_enum NOT NULL DEFAULT 'open',
  priority priority_enum NOT NULL DEFAULT 'medium',
  assigned_to BIGINT DEFAULT NULL,
  resolved_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_ticket_code UNIQUE (ticket_code),
  CONSTRAINT fk_tick_req FOREIGN KEY (requester_id) REFERENCES users (id),
  CONSTRAINT fk_tick_book FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE
  SET NULL,
    CONSTRAINT fk_tick_agent FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE
  SET NULL
);
CREATE TABLE ticket_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL,
  sender_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  is_internal BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tm_tick FOREIGN KEY (ticket_id) REFERENCES support_tickets (id) ON DELETE CASCADE,
  CONSTRAINT fk_tm_sender FOREIGN KEY (sender_id) REFERENCES users (id)
);
-- 7. Bảng REFUNDS (Hoàn tiền)
CREATE TABLE refunds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT NOT NULL,
  booking_id BIGINT NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  reason TEXT NOT NULL,
  status refund_status_enum NOT NULL DEFAULT 'pending',
  processed_by BIGINT DEFAULT NULL,
  processed_at TIMESTAMP DEFAULT NULL,
  gateway_ref VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ref_pay FOREIGN KEY (payment_id) REFERENCES payments (id),
  CONSTRAINT fk_ref_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
  CONSTRAINT fk_ref_processor FOREIGN KEY (processed_by) REFERENCES users (id) ON DELETE
  SET NULL
);
-- 8. Bảng COMMISSION_CONFIGS (Cấu hình hoa hồng)
CREATE TABLE commission_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  scope commission_scope_enum NOT NULL DEFAULT 'global',
  scope_value VARCHAR(100) DEFAULT NULL,
  commission_rate DECIMAL(5, 2) NOT NULL,
  min_commission DECIMAL(12, 2) DEFAULT NULL,
  max_commission DECIMAL(12, 2) DEFAULT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT NOT NULL,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cc_creat FOREIGN KEY (created_by) REFERENCES users (id)
);
-- 9. Bảng PLATFORM_FEE_CONFIGS (Cấu hình phí nền tảng)
CREATE TABLE platform_fee_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  fee_type discount_type_enum NOT NULL,
  fee_value DECIMAL(8, 4) NOT NULL,
  applies_to commission_scope_enum NOT NULL DEFAULT 'global',
  -- Reused Enum
  applies_value VARCHAR(100) DEFAULT NULL,
  min_fee DECIMAL(12, 2) DEFAULT NULL,
  max_fee DECIMAL(12, 2) DEFAULT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pfc_creat FOREIGN KEY (created_by) REFERENCES users (id)
);
-- 10. Bảng DISPUTES (Tranh chấp)
CREATE TABLE disputes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL,
  raised_by BIGINT NOT NULL,
  dispute_type VARCHAR(50) NOT NULL,
  -- cancellation, refund, property_issue, v.v.
  description TEXT NOT NULL,
  status ticket_status_enum NOT NULL DEFAULT 'open',
  -- Reused Enum
  resolution TEXT DEFAULT NULL,
  resolved_by BIGINT DEFAULT NULL,
  resolved_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_disp_book FOREIGN KEY (booking_id) REFERENCES bookings (id),
  CONSTRAINT fk_disp_raised FOREIGN KEY (raised_by) REFERENCES users (id),
  CONSTRAINT fk_disp_resolv FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE
  SET NULL
);
-- 11. Bảng STAFF_PROFILES (Hồ sơ nhân viên)
CREATE TABLE staff_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  employee_code VARCHAR(50) NOT NULL,
  department department_enum NOT NULL,
  job_title VARCHAR(200) NOT NULL,
  region_scope VARCHAR(200) DEFAULT NULL,
  city_scope JSONB DEFAULT NULL,
  manager_id BIGINT DEFAULT NULL,
  joined_at DATE DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_staff_user UNIQUE (user_id),
  CONSTRAINT uq_staff_emp UNIQUE (employee_code),
  CONSTRAINT fk_staff_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_staff_mgr FOREIGN KEY (manager_id) REFERENCES staff_profiles (id) ON DELETE
  SET NULL
);
-- 4. Bảng ROLE-BASED ACCESS CONTROL (RBAC)
CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  description TEXT DEFAULT NULL,
  is_system BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_role_slug UNIQUE (slug)
);
CREATE TABLE permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(100) NOT NULL,
  resource VARCHAR(100) NOT NULL,
  description TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_perm_act_res UNIQUE (action, resource)
);
CREATE TABLE role_permissions (
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
  CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);
-- 5. Bảng AUDIT_LOGS (Sử dụng JSONB để tối ưu)
CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id BIGINT NOT NULL,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id BIGINT NOT NULL,
  old_values JSONB DEFAULT NULL,
  new_values JSONB DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_actor ON audit_logs (actor_id);
-- 6. Bảng NOTIFICATIONS
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type VARCHAR(100) NOT NULL,
  channel VARCHAR(20) NOT NULL DEFAULT 'in_app',
  -- in_app, email, sms, push
  title VARCHAR(500) NOT NULL,
  body TEXT DEFAULT NULL,
  data JSONB DEFAULT NULL,
  entity_type VARCHAR(50) DEFAULT NULL,
  entity_id BIGINT DEFAULT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at TIMESTAMP DEFAULT NULL,
  sent_at TIMESTAMP DEFAULT NULL,
  failed_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_notif_user_read ON notifications (user_id, is_read, created_at);
-- ==========================================================
-- GIẢI PHÁP CHO CỘT updated_at (TRIGGER)
-- ==========================================================
-- Tạo function chung để cập nhật updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- Bảng định danh và hồ sơ
CREATE TRIGGER trg_users_updated_at BEFORE
UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_social_accounts_updated_at BEFORE
UPDATE ON social_accounts FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_partner_profiles_updated_at BEFORE
UPDATE ON partner_profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_customer_profiles_updated_at BEFORE
UPDATE ON customer_profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Bảng Properties và Rooms
CREATE TRIGGER trg_properties_updated_at BEFORE
UPDATE ON properties FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_room_types_updated_at BEFORE
UPDATE ON room_types FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_rooms_updated_at BEFORE
UPDATE ON rooms FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_amenities_updated_at BEFORE
UPDATE ON amenities FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Chính sách và Giá cả
CREATE TRIGGER trg_property_policies_updated_at BEFORE
UPDATE ON property_policies FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_rate_plans_updated_at BEFORE
UPDATE ON rate_plans FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_daily_rates_updated_at BEFORE
UPDATE ON daily_rates FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Khuyến mãi và Vouchers
CREATE TRIGGER trg_promotions_updated_at BEFORE
UPDATE ON promotions FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_vouchers_updated_at BEFORE
UPDATE ON vouchers FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Đặt phòng và Thanh toán
CREATE TRIGGER trg_bookings_updated_at BEFORE
UPDATE ON bookings FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_booking_rooms_updated_at BEFORE
UPDATE ON booking_rooms FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_booking_guests_updated_at BEFORE
UPDATE ON booking_guests FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_payments_updated_at BEFORE
UPDATE ON payments FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_refunds_updated_at BEFORE
UPDATE ON refunds FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Đánh giá (Reviews)
CREATE TRIGGER trg_reviews_updated_at BEFORE
UPDATE ON reviews FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_review_responses_updated_at BEFORE
UPDATE ON review_responses FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Tài chính (Wallets)
CREATE TRIGGER trg_payout_wallets_updated_at BEFORE
UPDATE ON payout_wallets FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_payout_requests_updated_at BEFORE
UPDATE ON payout_requests FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Cấu hình hệ thống (Configs)
CREATE TRIGGER trg_commission_configs_updated_at BEFORE
UPDATE ON commission_configs FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_platform_fee_configs_updated_at BEFORE
UPDATE ON platform_fee_configs FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_system_configs_updated_at BEFORE
UPDATE ON system_configs FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Hỗ trợ và Khiếu nại (Support)
CREATE TRIGGER trg_support_tickets_updated_at BEFORE
UPDATE ON support_tickets FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_ticket_messages_updated_at BEFORE
UPDATE ON ticket_messages FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_disputes_updated_at BEFORE
UPDATE ON disputes FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Phân quyền và Nhân sự (RBAC & Staff)
CREATE TRIGGER trg_roles_updated_at BEFORE
UPDATE ON roles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_permissions_updated_at BEFORE
UPDATE ON permissions FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_user_roles_updated_at BEFORE
UPDATE ON user_roles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_staff_profiles_updated_at BEFORE
UPDATE ON staff_profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_risk_rules_updated_at BEFORE
UPDATE ON risk_rules FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER trg_risk_assessments_updated_at BEFORE
UPDATE ON risk_assessments FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- 1. Tạo thêm các ENUM bị thiếu
CREATE TYPE ledger_type_enum AS ENUM ('earn', 'redeem', 'expire', 'adjust');
CREATE TYPE risk_decision_enum AS ENUM ('approve', 'flagged', 'review', 'reject');
CREATE TYPE dispute_type_enum AS ENUM ('cancellation', 'refund', 'property_issue', 'no_show', 'other');

-- 2. Đổi lại kiểu dữ liệu trong bảng tương ứng
ALTER TABLE loyalty_point_ledger 
  ALTER COLUMN type TYPE ledger_type_enum USING type::ledger_type_enum;

ALTER TABLE risk_assessments 
  ALTER COLUMN decision TYPE risk_decision_enum USING decision::risk_decision_enum;

ALTER TABLE disputes 
  ALTER COLUMN dispute_type TYPE dispute_type_enum USING dispute_type::dispute_type_enum;
  
-- Thêm index cho notifications bị thiếu (hỗ trợ join nhanh entity)
CREATE INDEX idx_notif_entity ON notifications (entity_type, entity_id);

-- Thêm index cho audit_logs bị thiếu (hỗ trợ lọc log theo thời gian)
CREATE INDEX idx_audit_created ON audit_logs (created_at);
SELECT count(*)
FROM information_schema.tables
WHERE table_schema = 'public';