ALTER TABLE bookings ADD COLUMN guest_name VARCHAR(100) DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN guest_email VARCHAR(100) DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN guest_phone VARCHAR(20) DEFAULT NULL;
